#include "endianness_config.h"

ENDIANNESS_CONFIG_STATIC uint16_t to_little_endian16(uint16_t value) {
	ENDIANNESS_CONFIG_VARS(2)

	ENDIANNESS_CONFIG_DATVALR(2, 0, 0)
	ENDIANNESS_CONFIG_DATVALR(2, 0, 1)

	return endian_data.integer_value;
}
ENDIANNESS_CONFIG_STATIC uint32_t to_little_endian32(uint32_t value) {
	ENDIANNESS_CONFIG_VARS(4)

	ENDIANNESS_CONFIG_DATVALR(4, 0, 0)
	ENDIANNESS_CONFIG_DATVALR(4, 0, 1)
	ENDIANNESS_CONFIG_DATVALR(4, 0, 2)
	ENDIANNESS_CONFIG_DATVALR(4, 0, 3)

	return endian_data.integer_value;
}
ENDIANNESS_CONFIG_STATIC uint64_t to_little_endian64(uint64_t value) {
	ENDIANNESS_CONFIG_VARS(8)

	ENDIANNESS_CONFIG_DATVALR(8, 0, 0)
	ENDIANNESS_CONFIG_DATVALR(8, 0, 1)
	ENDIANNESS_CONFIG_DATVALR(8, 0, 2)
	ENDIANNESS_CONFIG_DATVALR(8, 0, 3)
	ENDIANNESS_CONFIG_DATVALR(8, 0, 4)
	ENDIANNESS_CONFIG_DATVALR(8, 0, 5)
	ENDIANNESS_CONFIG_DATVALR(8, 0, 6)
	ENDIANNESS_CONFIG_DATVALR(8, 0, 7)

	return endian_data.integer_value;
}

ENDIANNESS_CONFIG_STATIC uint16_t to_big_endian16(uint16_t value) {
	ENDIANNESS_CONFIG_VARS(2)

	ENDIANNESS_CONFIG_DATVALR(2, 1, 0)
	ENDIANNESS_CONFIG_DATVALR(2, 1, 1)

	return endian_data.integer_value;
}
ENDIANNESS_CONFIG_STATIC uint32_t to_big_endian32(uint32_t value) {
	ENDIANNESS_CONFIG_VARS(4)

	ENDIANNESS_CONFIG_DATVALR(4, 1, 0)
	ENDIANNESS_CONFIG_DATVALR(4, 1, 1)
	ENDIANNESS_CONFIG_DATVALR(4, 1, 2)
	ENDIANNESS_CONFIG_DATVALR(4, 1, 3)

	return endian_data.integer_value;
}
ENDIANNESS_CONFIG_STATIC uint64_t to_big_endian64(uint64_t value) {
	ENDIANNESS_CONFIG_VARS(8)

	ENDIANNESS_CONFIG_DATVALR(8, 1, 0)
	ENDIANNESS_CONFIG_DATVALR(8, 1, 1)
	ENDIANNESS_CONFIG_DATVALR(8, 1, 2)
	ENDIANNESS_CONFIG_DATVALR(8, 1, 3)
	ENDIANNESS_CONFIG_DATVALR(8, 1, 4)
	ENDIANNESS_CONFIG_DATVALR(8, 1, 5)
	ENDIANNESS_CONFIG_DATVALR(8, 1, 6)
	ENDIANNESS_CONFIG_DATVALR(8, 1, 7)

	return endian_data.integer_value;
}

ENDIANNESS_CONFIG_STATIC uint16_t from_little_endian16(uint16_t value) {
	ENDIANNESS_CONFIG_VARS(2)

	ENDIANNESS_CONFIG_DATVALL(2, 0, 0)
	ENDIANNESS_CONFIG_DATVALL(2, 0, 1)

	return endian_data.integer_value;
}
ENDIANNESS_CONFIG_STATIC uint32_t from_little_endian32(uint32_t value) {
	ENDIANNESS_CONFIG_VARS(4)

	ENDIANNESS_CONFIG_DATVALL(4, 0, 0)
	ENDIANNESS_CONFIG_DATVALL(4, 0, 1)
	ENDIANNESS_CONFIG_DATVALL(4, 0, 2)
	ENDIANNESS_CONFIG_DATVALL(4, 0, 3)

	return endian_data.integer_value;
}
ENDIANNESS_CONFIG_STATIC uint64_t from_little_endian64(uint64_t value) {
	ENDIANNESS_CONFIG_VARS(8)

	ENDIANNESS_CONFIG_DATVALL(8, 0, 0)
	ENDIANNESS_CONFIG_DATVALL(8, 0, 1)
	ENDIANNESS_CONFIG_DATVALL(8, 0, 2)
	ENDIANNESS_CONFIG_DATVALL(8, 0, 3)
	ENDIANNESS_CONFIG_DATVALL(8, 0, 4)
	ENDIANNESS_CONFIG_DATVALL(8, 0, 5)
	ENDIANNESS_CONFIG_DATVALL(8, 0, 6)
	ENDIANNESS_CONFIG_DATVALL(8, 0, 7)

	return endian_data.integer_value;
}

ENDIANNESS_CONFIG_STATIC uint16_t from_big_endian16(uint16_t value) {
	ENDIANNESS_CONFIG_VARS(2)

	ENDIANNESS_CONFIG_DATVALL(2, 1, 0)
	ENDIANNESS_CONFIG_DATVALL(2, 1, 1)

	return endian_data.integer_value;
}
ENDIANNESS_CONFIG_STATIC uint32_t from_big_endian32(uint32_t value) {
	ENDIANNESS_CONFIG_VARS(4)

	ENDIANNESS_CONFIG_DATVALL(4, 1, 0)
	ENDIANNESS_CONFIG_DATVALL(4, 1, 1)
	ENDIANNESS_CONFIG_DATVALL(4, 1, 2)
	ENDIANNESS_CONFIG_DATVALL(4, 1, 3)

	return endian_data.integer_value;
}
ENDIANNESS_CONFIG_STATIC uint64_t from_big_endian64(uint64_t value) {
	ENDIANNESS_CONFIG_VARS(8)

	ENDIANNESS_CONFIG_DATVALL(8, 1, 0)
	ENDIANNESS_CONFIG_DATVALL(8, 1, 1)
	ENDIANNESS_CONFIG_DATVALL(8, 1, 2)
	ENDIANNESS_CONFIG_DATVALL(8, 1, 3)
	ENDIANNESS_CONFIG_DATVALL(8, 1, 4)
	ENDIANNESS_CONFIG_DATVALL(8, 1, 5)
	ENDIANNESS_CONFIG_DATVALL(8, 1, 6)
	ENDIANNESS_CONFIG_DATVALL(8, 1, 7)

	return endian_data.integer_value;
}